language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpstan analyze .

after_script:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor/
